name: deploy-latest
on:
  workflow_dispatch:
    inputs:
      release_name:
        type: string
        required: true
env:
  SSH_KEY: ${{secrets.DIGITAL_OCEAN_SSH_KEY}}
  SSH_HOST: ${{secrets.DIGITAL_OCEAN_HOST}}
  SSH_USER: ${{secrets.DIGITAL_OCEAN_USERNAME}}
  DOCKER_IMAGE_NAME: ${{vars.DOCKER_REPO_NAME}}/lolnuzlocke:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{secrets.DIGITAL_OCEAN_SSH_KEY}}
      - run: mkdir -p ~/.ssh
      - run: touch ~/.ssh/config
      - run: touch ~/.ssh/known_hosts
      - run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run: ssh $SSH_USER@$SSH_HOST docker login -u ${{vars.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}}
      - run: ssh $SSH_USER@$SSH_HOST docker ps -q --filter "name=lolnuzlocke" | xargs -r docker stop
      - run: ssh $SSH_USER@$SSH_HOST docker ps -aq --filter "name=lolnuzlocke" | xargs -r docker rm
      - run: ssh $SSH_USER@$SSH_HOST docker pull $DOCKER_IMAGE_NAME
      - run: ssh $SSH_USER@$SSH_HOST docker run -d --name lolnuzlocke -p 80:80 -e NUZLOCKE_ENVIRONMENT=PROD $DOCKER_IMAGE_NAME
