name: deploy
run-name: deploy ${{inputs.release_name}}
on:
  workflow_dispatch:
    inputs:
      release_name:
        type: string
        required: true
env:
  DOCKER_IMAGE_NAME: ${{vars.DOCKER_REPO_NAME}}/lolnuzlocke:${{inputs.release_name}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          port: 22
          key: ${{secrets.DIGITAL_OCEAN_SSH_KEY}}
          envs: DOCKER_IMAGE_NAME
          script: |
            docker login -u ${{vars.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}}
            docker ps -q --filter "name=lolnuzlocke" | xargs -r docker stop
            docker ps -aq --filter "name=lolnuzlocke" | xargs -r docker rm
            docker pull $DOCKER_IMAGE_NAME
            docker run -d --name lolnuzlocke -p 80:80 -e NUZLOCKE_ENVIRONMENT=PROD $DOCKER_IMAGE_NAME
