name: deploy
on:
  workflow_dispatch:
    inputs:
      release-name:
        description: "Name of release to deploy"
        required: true
        type: string
env:
  SSH_KEY: ${{secrets.DIGITAL_OCEAN_SSH_KEY}}
  SSH_HOST: ${{secrets.DIGITAL_OCEAN_HOST}}
  SSH_USER: ${{secrets.DIGITAL_OCEAN_USERNAME}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{secrets.DIGITAL_OCEAN_SSH_KEY}}
      - run: mkdir -p ~/.ssh
      - run: touch ~/.ssh/config
      - run: touch ~/.ssh/known_hosts
      - run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run: ssh $SSH_USER@$SSH_HOST touch /home/lolnuzlocke/helloworld.txt
