name: deploy
on:
  workflow_dispatch:
    inputs:
      release-name:
        description: "Name of release to deploy"
        required: true
        type: string
env:
  SSH_KEY: ${{secrets.DIGITAL_OCEAN_SSH_KEY}}
  SSH_HOST: ${{secrets.DIGITAL_OCEAN_HOST}}
  SSH_USER: ${{secrets.DIGITAL_OCEAN_USERNAME}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.ssh
      - run: echo $SSH_KEY > ~/.ssh/id_rsa
      - run: sudo chmod 600 ~/.ssh/id_rsa
      - run: ssh-keyscan $SSH_HOST
      - run: ssh $SSH_USER@$SSH_HOST touch /home/lolnuzlocke/helloworld.txt
