name: release-dist
on:
  push:
    branches:
      - release

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install python and poetry
        shell: bash
        run: pip install poetry==1.4.0
